[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npx serve dist -p $PORT -s"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
